# Generated by Django 2.2.6 on 2019-11-30 17:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Article',
            fields=[
                ('article_id', models.CharField(max_length=255, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('brand', models.CharField(max_length=255)),
                ('product_id', models.BigIntegerField()),
                ('product_category', models.CharField(max_length=255)),
            ],
            options={
                'db_table': 'article',
            },
        ),
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('email', models.EmailField(max_length=254)),
                ('first_name', models.CharField(max_length=255)),
                ('last_name', models.CharField(max_length=255)),
                ('stadt', models.CharField(max_length=255)),
                ('land', models.CharField(max_length=255)),
                ('plz', models.CharField(max_length=255)),
            ],
            options={
                'db_table': 'customers',
            },
        ),
        migrations.CreateModel(
            name='MonthlySalesBrand',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('month_year', models.CharField(max_length=255)),
                ('brand', models.CharField(max_length=255)),
                ('total_material_cost_of_brand', models.FloatField(null=True)),
                ('umsatz', models.FloatField(null=True)),
                ('anteil', models.FloatField(null=True)),
                ('materialquoten', models.FloatField(null=True)),
            ],
            options={
                'db_table': 'monthly_sales_brand',
            },
        ),
        migrations.CreateModel(
            name='MonthlySalesProduct',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('month_year', models.CharField(max_length=255)),
                ('article_id', models.CharField(max_length=255)),
                ('brand', models.CharField(max_length=255, null=True)),
                ('units_sold', models.IntegerField(null=True)),
                ('month_year_materialcost', models.FloatField(null=True)),
                ('total_material_cost', models.FloatField(null=True)),
                ('total_product_sales', models.FloatField(null=True)),
                ('quote', models.FloatField(null=True)),
            ],
            options={
                'db_table': 'monthly_sales_product',
            },
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('order_id', models.CharField(max_length=255, primary_key=True, serialize=False)),
                ('amazon_order_id', models.CharField(max_length=255, null=True)),
                ('e_mail', models.EmailField(max_length=254)),
                ('date', models.DateField()),
                ('time', models.TimeField()),
                ('total_gross_before_discount', models.FloatField(null=True)),
                ('total_product_gross_before_discount', models.FloatField(null=True)),
                ('shipping_net', models.FloatField(null=True)),
                ('shipping_tax', models.FloatField(null=True)),
                ('discount', models.FloatField(null=True)),
                ('total_gross_after_discount', models.FloatField(null=True)),
                ('total_product_gross_after_discount', models.FloatField(null=True)),
                ('total_tax', models.FloatField(null=True)),
                ('total_product_tax', models.FloatField(null=True)),
                ('total_product_net_after_discount', models.FloatField(null=True)),
                ('total_net_after_discount', models.FloatField(null=True)),
                ('total_product_net_before_discount', models.FloatField(null=True)),
                ('product_tax_category_19', models.FloatField(null=True)),
                ('product_tax_category_7', models.FloatField(null=True)),
                ('coupon_code', models.CharField(max_length=255)),
                ('payment_method', models.CharField(max_length=255)),
                ('customer_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sales_data.Customer')),
            ],
            options={
                'db_table': 'orders',
            },
        ),
        migrations.CreateModel(
            name='Order_Detail',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('article_id', models.CharField(max_length=255)),
                ('price', models.FloatField(null=True)),
                ('quantity', models.IntegerField(null=True)),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sales_data.Order')),
            ],
            options={
                'db_table': 'order_detail',
            },
        ),
    ]
