# Generated by Django 2.2.6 on 2019-11-30 17:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sales_data', '0003_auto_20191130_1748'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='customer_id',
            new_name='customer',
        ),
    ]
