# Generated by Django 2.2.6 on 2019-11-30 19:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales_data', '0005_auto_20191130_1930'),
    ]

    operations = [
        migrations.RenameField(
            model_name='article',
            old_name='name',
            new_name='article_name',
        ),
        migrations.RenameField(
            model_name='article',
            old_name='product_category',
            new_name='country',
        ),
        migrations.AddField(
            model_name='article',
            name='kostenfrei',
            field=models.CharField(default=1, max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='article',
            name='product_name',
            field=models.CharField(default=2, max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='article',
            name='variable',
            field=models.CharField(default=1, max_length=255),
            preserve_default=False,
        ),
    ]
