# Generated by Django 2.2.6 on 2019-11-30 21:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales_data', '0006_auto_20191130_1958'),
    ]

    operations = [
        migrations.RenameField(
            model_name='article',
            old_name='kostenfrei',
            new_name='giveaway',
        ),
        migrations.RenameField(
            model_name='article',
            old_name='variable',
            new_name='variant',
        ),
        migrations.AddField(
            model_name='customer',
            name='shop_customer_id',
            field=models.CharField(default=23123, max_length=255),
            preserve_default=False,
        ),
    ]
