# Generated by Django 2.2.6 on 2019-11-30 21:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales_data', '0007_auto_20191130_2108'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='repeated_customer',
            field=models.CharField(default=123, max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='order',
            name='shop_view',
            field=models.CharField(default=23, max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='order',
            name='status',
            field=models.CharField(default=12341, max_length=255),
            preserve_default=False,
        ),
    ]
