# Generated by Django 2.2.6 on 2019-12-03 15:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales_data', '0008_auto_20191130_2115'),
    ]

    operations = [
        migrations.CreateModel(
            name='Withdrawl',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('date', models.DateField()),
                ('article_id', models.CharField(max_length=255)),
                ('units', models.IntegerField()),
            ],
            options={
                'db_table': 'withdrawls',
            },
        ),
    ]
