# Generated by Django 2.2.6 on 2019-12-05 00:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales_data', '0009_withdrawl'),
    ]

    operations = [
        migrations.CreateModel(
            name='ShopviewChannel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('shopview', models.CharField(max_length=255)),
                ('channel', models.CharField(max_length=255)),
            ],
            options={
                'db_table': 'shopview_channel',
            },
        ),
    ]
