# Generated by Django 2.2.6 on 2019-12-11 02:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales_data', '0010_shopviewchannel'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='product_id',
            field=models.BigIntegerField(null=True),
        ),
    ]
